apiVersion: v1
kind: Service
metadata: 
  name: director-service
spec:
  selector:
    app.kubernetes.io/name: director
  type: LoadBalancer
  loadBalancerIP: 10.0.0.60
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
